version: "3.8"

services:
  wordpress:
    container_name: index_search_wordpress
    restart: always
    build:
      context: ./config/development

    ports:
      - ${WORDPRESS_LOCALHOST_PORT}:80
      - 9003:9003

    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_NAME} # Same as db name.
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_NAME} # Same as db name.
      WORDPRESS_SKIP_INSTALL: "yes"
      # Set the XDEBUG_CONFIG as described here: https://xdebug.org/docs/all_settings#XDEBUG_CONFIG
      XDEBUG_CONFIG: client_host=192.168.1.2 # This is for XDebug 3.

    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--output",
          "/dev/null",
          "--silent",
          "--fail",
          "http://localhost:80",
        ]
      interval: 1s
      timeout: 1s
      retries: 30

    tmpfs:
      - /var/www/html

    volumes:
      # - wordpress:/var/www/html
      - ./:/var/www/html/wp-content/plugins/indexed-search

    depends_on:
      - database

  database:
    container_name: index_search_database
    image: mariadb:10.8
    restart: always

    ports:
      - "${WORDPRESS_DB_LOCALHOST_PORT}:3306"

    environment:
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_USER: ${WORDPRESS_DB_NAME} # Same as db name.
      MYSQL_PASSWORD: ${WORDPRESS_DB_NAME} # Same as db name.
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME} # Same as db name.

    healthcheck:
      test:
        [
          "CMD",
          "mysqlshow",
          "-u${WORDPRESS_DB_USER}",
          "-p${WORDPRESS_DB_PASSWORD}",
          "${WORDPRESS_DB_NAME}",
        ]
      interval: 1s
      timeout: 1s
      retries: 30

    tmpfs:
      - /var/lib/mysql

    volumes:
      - ./tests/_data/dump.sql:/docker-entrypoint-initdb.d/datadump.sql
